[package]
name = "c3"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/c3.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"

# for test
# [dev-dependencies]
# tree-sitter = "0.26.3"
# tree-sitter-c3 = { path = "../tree-sitter-c3" }
