id = "c3"
name = "C3"
version = "0.0.3"
schema_version = 1
authors = ["Aiden Olsen <olsenaiden33@gmail.com>"]
description = "This extension bring basic c3 language support to zed. NOTE: This extension is still a WIP!"
repository = "https://github.com/AineeJames/c3-zed"

[language_servers.c3]
name = "c3"
language = "C3"

[grammars.c3]
repository = "https://github.com/fernandolguevara/tree-sitter-c3"
rev = "next"

# for test
# repository = "file:///Users/f00lg/github/c3/tree-sitter-c3"
# rev="next"
